name: Deploy on Render

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  deploy_services:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Deploy Frontend
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: srv-courlb8l6cac73b9oq9g
          api_key: rnd_HFNv4gEpeHFphaRJAKEQZiduMB5v
      - name: Deploy  Backend
      - uses: JorgeLNJunior/render-deploy@v1.4.4
        with:
          service_id: srv-cout40nsc6pc73aqobpg
          api_key: rnd_HFNv4gEpeHFphaRJAKEQZiduMB5v
