name: Run Tests

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-20.04
    env:
      PROJECT_PATH: frontend/client

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: dev  # Checkout the dev branch
    - name: Install dependencies
      run: npm install
      working-directory: ${{ github.workspace }}/${{ env.PROJECT_PATH }}

    - name: Run tests
      run:  npm test -- App.test.js --test-skip
      working-directory: ${{ github.workspace }}/${{ env.PROJECT_PATH }}
