name: Run Tests

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        ref: dev  # Checkout the dev branch
        path: frontend/client
    - name: Check directory
      run: |
        pwd
        ls -la
    - name: Install dependencies
      run: cd frontend/client && npm install

    - name: Run tests
      run: cd frontend/client && npm test
