name: Run Tests

on:
  push:
    branches:
      - dev
  workflow_dispatch:  # Manually trigger the workflow

jobs:
  test:
    name: Run unit tests
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        ref: dev  # Checkout the dev branch

    - name: Debug Directory Structure
      run: ls -la

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Change directory to frontend/client
      run: cd frontend/client

    - name: Debug Package.json Contents
      run: cat package.json || echo "No package.json found"

    - name: Install dependencies
      run: npm install

    - name: Run tests
      run: npm test
